FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04

RUN apt-get update && apt-get install -y python3 python3-pip sudo

RUN pip3 install --upgrade pip

ENV PYTHONPATH="$PYTHONPATH:/app"

COPY . /app

WORKDIR /app

RUN pip3 install -r requirements.txt





